name: Dependabot auto-merge

on:
  pull_request_target:
    branches:
      - main

permissions: {}

jobs:
  dependabot-automerge:
    permissions:
      contents: read
      pull-requests: read
    uses: petry-projects/.github/.github/workflows/dependabot-automerge-reusable.yml@dependabot-automerge/stable
    secrets: inherit
