name: Dependabot auto-merge

on:
  pull_request_target:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-automerge:
    permissions:
      contents: read
      pull-requests: read
    uses: petry-projects/.github/.github/workflows/dependabot-automerge-reusable.yml@v2
    secrets: inherit
